# Site
repository: xaany/my_cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Даниил Русович
title: Middle Python Backend developer
email: aiky.77777@gmail.com
# website: www.github.com/xaany/my_cv

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  xaany
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: t.me
  icon: fas fa-paper-plane
  url: https://t.me/xaaaan
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Обо мне
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Привет! Меня зовут Даниил, я Middle Python Backend разработчик. 
  Я начал свой путь программиста 5 лет назад. За это время успел поработать в нескольких небольших командах и получить огромный опыт.

  Так же у меня есть знания в области:
   - <mark>FrontEnd</mark>
   - <mark>Linux</mark>
   - <mark>GitHub</mark>

content:
  - title: Навыки # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Parsing/Scarping
        sub_title: Работа с данными
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Я написал множество парсеров/скраперов/ботов. Работал с http-запросами (aiohttp), куками, проксями, капчей, <mark>Selenium</mark>. Умею анализировать ресурс и вытаскивать запросы
      
      - layout: left
        title: Databases & Cache
        sub_title: Проектирование бд, составление запросов
        description: |
          Я часто работал с такими базами данных как Postgres, MySQL, SQLite. Использовал <mark>Alembic</mark>, <mark>sqlalchemy</mark>. Так же использовал <mark>Redis</mark> в своих разработках

      - layout: left
        title: FastAPI & DRF
        sub_title: Составление API
        description: |
          Я создавал API различных видов. Писал API под Front-end. Работал с сессиями и авторизацией (в том числе JWT). Немного работал с <mark>DRF</mark>. Но в основном отдаю предпочтение <mark>FastAPI</mark>

      - layout: left
        title: Telegram Bot API
        sub_title: Clear API & aiogram 2/3
        description: |
          Я написал огромное количество ботов для телеграма, особенно с использованием асинхронной библиотеки <mark>aiogram</mark>

      - layout: left
        title: HTML/CSS/JS
        sub_title: FrontEnd разработка
        description: |
          Я владею навыками web'а. Могу написать несложный FrontEnd. Знаком с такими фреймворками как <mark>VueJS</mark>, <mark>Django</mark>. Чаще всего использовал Boostrap для того, чтобы быстро накидать шаблон страницы


  - title: Опыт # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TG HStudio
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Programmer
        caption: Июнь 2021 - Ноябрь 2023
        quote: >
          Разработка решений для малого и среднего бизнеса в Телеграм, например создание ботов-магазинов или ботов-поддержки и тп.
        description: | # this will include new lines to allow paragraphs
            Наша небольшая компания занималась разработкой ботов для бизнеса. Итегрировали сторонние API, занимались сбором и анализом данных. За время работы в компании мы создали более 100 ботов различной тематики и функционала.

      - layout: left
        title: Freelance
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Самозанятый
        caption: Ноябрь 2023 - Текущее время
        quote: >
          Разработка проектов разной направленности
        description: | # this will include new lines to allow paragraphs
            В данный момент я являюсь самозанятым. Выполняю заказы на различных форумах и биржах. Получил "признание" на одном из форумов среди программистов. В основном, получаю заказы, связанные с работой с куками, базами данных, парсинг и автоматизация рутинных процессов (чаще на http-запросах, селениум использую редко)

  - title: Образование # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Сибирский Федеральный Университет
        caption: 2019 - 2023
        sub_title: Институт Космических и Информационных Технологий
        quote: >
          Сибирский федеральный университет (СФУ) входит в топ-15 вузов России. Первый в России федеральный университет. Крупный научно-исследовательский и образовательный центр в России. Крупнейший университет восточной части России.
        description: | # this will include new lines to allow paragraphs
          Имею неоконченное высшее (4 курса) бакалаврское образование по направлению "Управление в технических системах". Обучаясь в университете, я получил множество полезных навыков, которые применяю и по сей день. Был лидером на кафедре по предмету "Программирование".

  - title: Немного информации обо мне
    layout: text
    content: | # this will include new lines to allow paragraphs
      Мне 23 года. Родился в России г. Красноярск. В 2023 году переехал из России в Таиланд (прожил на Пхукете год). В данный момент живу в Грузии, в Батуми.
      Я очень общительный и дружелюбный человек. Открыт ко всему новому, особенно в плане кодинга. 
      
      Хорошо воспринимаю техническую информацию, люблю разбираться в документации.

      Отлично разбираюсь в криптовалюте ( Пробовал себя в торговле на фьючерсах. В данный момент только спот :)) ). Пробовал писать свои контракты.

      В университете активно изучал C++ и далее - C#. Прекрасно знаю ООП и применяю знания на практике по сей день.
      
      Знаю английский язык на уровень B1-B2 (углубленное изучение языка было в школе с 2 по 11 класс и практика с нейтивами позднее).
      
      Люблю:
      - Все что связано с компьютерным железом
      - Спорт (тренажерный зал)
      - Море
      - Жаркую погоду

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
